// packages/react/src/chart-frame.tsx
import type { DataTable } from '@silverpoint/core';
import type { RenderedChart } from '@silverpoint/grounds';
import type { HTMLAttributes, ReactNode, Ref } from 'react';
import { ChartSvg } from './chart-svg';

function Table({ table, id, visibility }: { readonly table: DataTable; readonly id: string; readonly visibility: string }) {
  return (
    <div className="sp-table-box" data-visibility={visibility}>
      <table className="sp-table" id={id} data-visibility={visibility}>
        <caption>{table.caption}</caption>
        <thead>
          <tr>
            {table.columns.map((column, index) => (
              <th key={index} scope="col">
                {column}
              </th>
            ))}
          </tr>
        </thead>
        <tbody>
          {table.rows.map((row, index) => (
            <tr key={index}>
              {row.map((cell, column) =>
                column === 0 ? (
                  <th key={column} scope="row">
                    {cell}
                  </th>
                ) : (
                  <td key={column}>{cell}</td>
                ),
              )}
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}

export interface ChartFrameProps {
  readonly rendered: RenderedChart;
  readonly className?: string;
  /** Interaction handlers and focus attributes, supplied by the client component only. */
  readonly rootProps?: HTMLAttributes<HTMLDivElement>;
  readonly rootRef?: Ref<HTMLDivElement>;
  /** Readout and marker, drawn over the chart by the client component. */
  readonly overlay?: ReactNode;
}

/** The chart's DOM: root, SVG, overlay and tabular alternative (API Spec §10). */
export function ChartFrame({ rendered, className, rootProps, rootRef, overlay }: ChartFrameProps) {
  const classes = ['sp-root', `sp-ground-${rendered.ground}`, className].filter(Boolean).join(' ');
  return (
    <div
      className={classes}
      data-substrate={rendered.substrate}
      data-chrome={rendered.chrome}
      data-status={rendered.status}
      ref={rootRef}
      {...rootProps}
    >
      <ChartSvg view={rendered.view} />
      {overlay}
      {rendered.dataTable !== 'none' && (
        <Table table={rendered.table} id={rendered.ids.table} visibility={rendered.dataTable} />
      )}
    </div>
  );
}

// packages/vue/src/ChartFrame.vue
<script setup lang="ts">
import type { RenderedChart } from '@silverpoint/grounds';
import ChartSvg from './ChartSvg.vue';

/** The chart's DOM: root, SVG, overlay slot and tabular alternative (API Spec §10). */
defineProps<{ rendered: RenderedChart; rootClass: string }>();
</script>

<template>
  <div
    :class="rootClass"
    :data-substrate="rendered.substrate"
    :data-chrome="rendered.chrome"
    :data-status="rendered.status"
  >
    <ChartSvg :view="rendered.view" />
    <slot />
    <div v-if="rendered.dataTable !== 'none'" class="sp-table-box" :data-visibility="rendered.dataTable">
      <table
        class="sp-table"
        :id="rendered.ids.table"
        :data-visibility="rendered.dataTable"
      >
        <caption>{{ rendered.table.caption }}</caption>
        <thead>
          <tr>
            <th v-for="(column, index) in rendered.table.columns" :key="index" scope="col">{{ column }}</th>
          </tr>
        </thead>
        <tbody>
          <tr v-for="(row, index) in rendered.table.rows" :key="index">
            <template v-for="(cell, column) in row" :key="column">
              <th v-if="column === 0" scope="row">{{ cell }}</th>
              <td v-else>{{ cell }}</td>
            </template>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</template>
