// packages/vue/src/SpLineChart.vue
<script setup lang="ts">
import {
  instanceId,
  lineChart,
  reduceInteraction,
  type ActiveItem,
  type InteractionEvent,
  type LineChartProps,
  type PointerKind,
  type Readout,
} from '@silverpoint/core';
import { renderChart, toSVGString } from '@silverpoint/grounds';
import { computed, ref, useId } from 'vue';
import ChartFrame from './ChartFrame.vue';
import ChartOverlay from './ChartOverlay.vue';
import { useForcedPrecision, useMeasuredWidth, useProvider, useTypefaceCheck } from './environment';

/** `SpLineChart` (REQ-060): the same props as React's `LineChart`, name for name (API Spec §4). */
const props = defineProps<LineChartProps>();

const emit = defineEmits<{
  activeChange: [item: ActiveItem | null];
  select: [item: ActiveItem];
}>();

defineSlots<{ tooltip?: (scope: { active: ActiveItem; readout: Readout }) => unknown }>();

// Vue's useId counts per application, so a server render and the hydrating client agree (REQ-109).
const generated = useId();
const provider = useProvider();
const forcedPrecision = useForcedPrecision();
useTypefaceCheck(lineChart.name);
const root = ref<{ $el: HTMLElement }>();
const element = computed(() => root.value?.$el);
const measured = useMeasuredWidth(element, () => props.width === undefined);

const rendered = computed(() =>
  renderChart(lineChart, props, {
    id: instanceId(lineChart.name, generated),
    width: measured.value,
    provider,
    forcedPrecision: forcedPrecision.value,
  }),
);

const rootClass = computed(() =>
  ['sp-root', `sp-ground-${rendered.value.ground}`, props.className].filter(Boolean).join(' '),
);

// The active item is interaction state REQ-141 requires; see the phase-0 ledger on REQ-108.
const active = ref<ActiveItem | null>(null);

function dispatch(event: InteractionEvent): boolean {
  const result = reduceInteraction(rendered.value.geometry, active.value, event);
  if (result.changed) {
    active.value = result.active;
    emit('activeChange', result.active);
  }
  if (result.selected) emit('select', result.selected);
  return result.handled;
}

function onPointer(type: 'pointer' | 'click', event: PointerEvent | MouseEvent): void {
  const svg = element.value?.querySelector('svg.sp-chart');
  if (!svg) return;
  const box = svg.getBoundingClientRect();
  dispatch({
    type,
    client: { x: event.clientX, y: event.clientY },
    box: { left: box.left, top: box.top, width: box.width, height: box.height },
    kind: (('pointerType' in event && event.pointerType) || 'mouse') as PointerKind,
  });
}

function onKeydown(event: KeyboardEvent): void {
  if (dispatch({ type: 'key', key: event.key })) event.preventDefault();
}

defineExpose({
  getGeometry: () => rendered.value.geometry,
  toSVGString: () => toSVGString(rendered.value),
});
</script>

<template>
  <ChartFrame
    ref="root"
    :rendered="rendered"
    :root-class="rootClass"
    tabindex="0"
    role="group"
    :aria-label="rendered.name"
    @pointermove="onPointer('pointer', $event)"
    @pointerdown="onPointer('pointer', $event)"
    @click="onPointer('click', $event)"
    @pointerleave="dispatch({ type: 'leave' })"
    @focus="dispatch({ type: 'focus' })"
    @blur="dispatch({ type: 'blur' })"
    @keydown="onKeydown"
  >
    <ChartOverlay :rendered="rendered" :active="active">
      <template v-if="$slots.tooltip" #tooltip="scope">
        <slot name="tooltip" v-bind="scope" />
      </template>
    </ChartOverlay>
  </ChartFrame>
</template>

// packages/angular/line-chart/sp-line-chart.ts
import { ChangeDetectionStrategy, Component, computed, contentChild, inject, input, output, signal } from '@angular/core';
import {
  injectForcedPrecision,
  injectMeasuredWidth,
  SILVERPOINT_CONFIG,
  SilverpointIds,
  SpChartFrame,
  SpChartOverlay,
  SpTooltip,
} from '@silverpoint/angular';
import {
  instanceId,
  lineChart,
  reduceInteraction,
  type ActiveItem,
  type Geometry,
  type InteractionEvent,
  type LineChartProps,
  type PointerKind,
} from '@silverpoint/core';
import { renderChart, toSVGString } from '@silverpoint/grounds';

type Prop<K extends keyof LineChartProps> = LineChartProps[K];

/**
 * `<sp-line-chart>` (REQ-060): standalone, signal inputs, OnPush (REQ-101). Inputs are named
 * as in every other adapter (API Spec §4).
 */
@Component({
  selector: 'sp-line-chart',
  imports: [SpChartFrame, SpChartOverlay],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <sp-chart-frame [rendered]="rendered()" [rootClass]="rootClass()" [interactive]="true" (rootEvent)="onRootEvent($event)">
      <sp-chart-overlay [rendered]="rendered()" [active]="active()" [tooltip]="tooltip()?.template" />
    </sp-chart-frame>
  `,
})
export class SpLineChart {
  readonly data = input<Prop<'data'>>();
  readonly ground = input<Prop<'ground'>>();
  readonly substrate = input<Prop<'substrate'>>();
  readonly mode = input<Prop<'mode'>>();
  readonly seed = input<Prop<'seed'>>();
  readonly id = input<Prop<'id'>>();
  readonly height = input<Prop<'height'>>();
  readonly width = input<Prop<'width'>>();
  readonly chrome = input<Prop<'chrome'>>();
  readonly hatchFill = input<Prop<'hatchFill'>>();
  readonly title = input<Prop<'title'>>();
  readonly badge = input<Prop<'badge'>>();
  readonly value = input<Prop<'value'>>();
  readonly unit = input<Prop<'unit'>>();
  readonly footerLeft = input<Prop<'footerLeft'>>();
  readonly footerRight = input<Prop<'footerRight'>>();
  readonly label = input<Prop<'label'>>();
  readonly description = input<Prop<'description'>>();
  readonly dataTable = input<Prop<'dataTable'>>();
  readonly locale = input<Prop<'locale'>>();
  readonly numberFormat = input<Prop<'numberFormat'>>();
  readonly className = input<Prop<'className'>>();
  readonly xKey = input<Prop<'xKey'>>();
  readonly valueKey = input<Prop<'valueKey'>>();
  readonly secondaryKey = input<Prop<'secondaryKey'>>();
  readonly curve = input<Prop<'curve'>>();
  readonly series = input<Prop<'series'>>();
  readonly connectNulls = input<Prop<'connectNulls'>>();

  /** The active item changed, or `null` when it cleared (REQ-141, REQ-143). */
  readonly activeChange = output<ActiveItem | null>();
  /** An item was chosen by click, Enter or Space (API Spec §9). */
  readonly select = output<ActiveItem>();

  private readonly provider = inject(SILVERPOINT_CONFIG, { optional: true }) ?? {};
  private readonly generated = inject(SilverpointIds).next();
  private readonly forcedPrecision = injectForcedPrecision();
  private readonly measured = injectMeasuredWidth(() => this.width() === undefined);

  private readonly props = computed<LineChartProps>(() => ({
    data: this.data(),
    ground: this.ground(),
    substrate: this.substrate(),
    mode: this.mode(),
    seed: this.seed(),
    id: this.id(),
    height: this.height(),
    width: this.width(),
    chrome: this.chrome(),
    hatchFill: this.hatchFill(),
    title: this.title(),
    badge: this.badge(),
    value: this.value(),
    unit: this.unit(),
    footerLeft: this.footerLeft(),
    footerRight: this.footerRight(),
    label: this.label(),
    description: this.description(),
    dataTable: this.dataTable(),
    locale: this.locale(),
    numberFormat: this.numberFormat(),
    className: this.className(),
    xKey: this.xKey(),
    valueKey: this.valueKey(),
    secondaryKey: this.secondaryKey(),
    curve: this.curve(),
    series: this.series(),
    connectNulls: this.connectNulls(),
  }));

  protected readonly rendered = computed(() =>
    renderChart(lineChart, this.props(), {
      id: instanceId(lineChart.name, this.generated),
      width: this.measured(),
      provider: this.provider,
      forcedPrecision: this.forcedPrecision(),
    }),
  );

  protected readonly rootClass = computed(() =>
    ['sp-root', `sp-ground-${this.rendered().ground}`, this.className()].filter(Boolean).join(' '),
  );

  /** A consumer-supplied readout template (REQ-142). */
  protected readonly tooltip = contentChild(SpTooltip);
  /** The active item: interaction state REQ-141 requires. */
  protected readonly active = signal<ActiveItem | null>(null);

  private readonly dispatch = (event: InteractionEvent): boolean => {
    const result = reduceInteraction(this.rendered().geometry, this.active(), event);
    if (result.changed) {
      this.active.set(result.active);
      this.activeChange.emit(result.active);
    }
    if (result.selected) this.select.emit(result.selected);
    return result.handled;
  };

  /** Turns a DOM event of the chart root into a core interaction event; decides nothing. */
  protected readonly onRootEvent = (event: Event): void => {
    const root = event.currentTarget as HTMLElement | null;
    switch (event.type) {
      case 'pointermove':
      case 'pointerdown':
      case 'click': {
        const svg = root?.querySelector('svg.sp-chart');
        if (!svg) return;
        const box = svg.getBoundingClientRect();
        const pointer = event as PointerEvent;
        this.dispatch({
          type: event.type === 'click' ? 'click' : 'pointer',
          client: { x: pointer.clientX, y: pointer.clientY },
          box: { left: box.left, top: box.top, width: box.width, height: box.height },
          kind: (pointer.pointerType || 'mouse') as PointerKind,
        });
        return;
      }
      case 'pointerleave':
        this.dispatch({ type: 'leave' });
        return;
      case 'focus':
      case 'blur':
        this.dispatch({ type: event.type });
        return;
      case 'keydown':
        if (this.dispatch({ type: 'key', key: (event as KeyboardEvent).key })) event.preventDefault();
    }
  };

  /** The rendered geometry (API Spec §8.2, symmetric with `ChartHandle`). */
  getGeometry(): Geometry {
    return this.rendered().geometry;
  }

  /** The canonical SVG markup of the chart. */
  toSVGString(): string {
    return toSVGString(this.rendered());
  }
}
