// examples/angular/src/main.ts
import { NgComponentOutlet } from '@angular/common';
import { ChangeDetectionStrategy, Component, provideZonelessChangeDetection, type Type } from '@angular/core';
import { bootstrapApplication } from '@angular/platform-browser';
import { SpLineChart } from '@silverpoint/angular/line-chart';
import { SpBulletChart } from '@silverpoint/angular/bullet-chart';
import { SpPyramidChart } from '@silverpoint/angular/pyramid-chart';
import { SpHeatmapChart } from '@silverpoint/angular/heatmap-chart';
import { SpTreemapChart } from '@silverpoint/angular/treemap-chart';
import { SpSankeyChart } from '@silverpoint/angular/sankey-chart';
import { SpActivityGrid } from '@silverpoint/angular/activity-grid';
import { SpStepChart } from '@silverpoint/angular/step-chart';
import { SpSparklineRows } from '@silverpoint/angular/sparkline-rows';
import { SpKpiCard } from '@silverpoint/angular/kpi-card';
import { SpBarChart } from '@silverpoint/angular/bar-chart';
import { SpStackedBarChart } from '@silverpoint/angular/stacked-bar-chart';
import { SpComposedChart } from '@silverpoint/angular/composed-chart';
import { SpWaterfallChart } from '@silverpoint/angular/waterfall-chart';
import { SpFunnelChart } from '@silverpoint/angular/funnel-chart';
import { SpCandlestickChart } from '@silverpoint/angular/candlestick-chart';
import { SpAreaChart } from '@silverpoint/angular/area-chart';
import { SpRangeBandChart } from '@silverpoint/angular/range-band-chart';
import { SpStreamChart } from '@silverpoint/angular/stream-chart';
import { SpScatterChart } from '@silverpoint/angular/scatter-chart';
import { SpBubbleChart } from '@silverpoint/angular/bubble-chart';
import { SpDonutChart } from '@silverpoint/angular/donut-chart';
import { SpRadarChart } from '@silverpoint/angular/radar-chart';
import { SpPolarBarChart } from '@silverpoint/angular/polar-bar-chart';
import { SpRadialArcGroup } from '@silverpoint/angular/radial-arc-group';
import { SpRadialRings } from '@silverpoint/angular/radial-rings';
import { SpGaugeArc } from '@silverpoint/angular/gauge-arc';
import { SpMeterChart } from '@silverpoint/angular/meter-chart';
import { SpCoxcombChart } from '@silverpoint/angular/coxcomb-chart';
import { SpWindRose } from '@silverpoint/angular/wind-rose';
import { SpVolvelleChart } from '@silverpoint/angular/volvelle-chart';
import { SpChordRing } from '@silverpoint/angular/chord-ring';
import { SpOrbitChart } from '@silverpoint/angular/orbit-chart';
import { DEMO_PROPS, fixtureById, fixtureProps, GALLERY, sizeOf, wantsGallery } from '@silverpoint/example-harness';

const fixture = fixtureById(new URLSearchParams(location.search).get('fixture'));

/** Every chart a fixture can name, by its chart name. */
const CHARTS: Readonly<Record<string, Type<unknown>>> = { LineChart: SpLineChart, BulletChart: SpBulletChart, PyramidChart: SpPyramidChart, HeatmapChart: SpHeatmapChart, TreemapChart: SpTreemapChart, SankeyChart: SpSankeyChart, ActivityGrid: SpActivityGrid, StepChart: SpStepChart, SparklineRows: SpSparklineRows, KpiCard: SpKpiCard, BarChart: SpBarChart, StackedBarChart: SpStackedBarChart, ComposedChart: SpComposedChart, WaterfallChart: SpWaterfallChart, FunnelChart: SpFunnelChart, CandlestickChart: SpCandlestickChart, AreaChart: SpAreaChart, RangeBandChart: SpRangeBandChart, StreamChart: SpStreamChart, ScatterChart: SpScatterChart, BubbleChart: SpBubbleChart, DonutChart: SpDonutChart, RadarChart: SpRadarChart, PolarBarChart: SpPolarBarChart, RadialArcGroup: SpRadialArcGroup, RadialRings: SpRadialRings, GaugeArc: SpGaugeArc, MeterChart: SpMeterChart, CoxcombChart: SpCoxcombChart, WindRose: SpWindRose, VolvelleChart: SpVolvelleChart, ChordRing: SpChordRing, OrbitChart: SpOrbitChart };

@Component({
  selector: 'app-root',
  imports: [SpLineChart, NgComponentOutlet],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    @if (gate) {
      <main>
        <div class="sp-harness" data-gate="" [attr.data-size]="gate.size">
          <ng-container *ngComponentOutlet="gate.component; inputs: gate.inputs" />
        </div>
      </main>
    } @else if (gallery) {
      <main>
        <h1>silverpoint · Angular · gallery</h1>
        <div class="sp-gallery">
          @for (item of gallery; track item.chart) {
            <div class="sp-harness" data-size="md">
              <ng-container *ngComponentOutlet="item.component; inputs: item.inputs" />
            </div>
          }
        </div>
      </main>
    } @else {
      <main>
        <h1>silverpoint · Angular</h1>
        <div class="sp-harness" data-size="md">
          <sp-line-chart
            [id]="demo.id" [width]="demo.width" [title]="demo.title" [badge]="demo.badge" [value]="demo.value"
            [unit]="demo.unit" [footerLeft]="demo.footerLeft" [footerRight]="demo.footerRight"
          />
        </div>
      </main>
    }
  `,
})
class App {
  protected readonly gate = fixture ? { component: CHARTS[fixture.chart] as Type<unknown>, inputs: fixtureProps(fixture), size: sizeOf(fixture) } : undefined;
  protected readonly gallery = wantsGallery(location.search)
    ? GALLERY.map(({ chart, props }) => ({ chart, component: CHARTS[chart] as Type<unknown>, inputs: props }))
    : undefined;
  protected readonly demo = DEMO_PROPS;
}

bootstrapApplication(App, { providers: [provideZonelessChangeDetection()] }).catch((error: unknown) => console.error(error));

// examples/vite-react/src/main.tsx
import type { ComponentType } from 'react';
import '@silverpoint/fonts/fonts.css';
import '@silverpoint/grounds/styles.css';
import '@silverpoint/example-harness/harness.css';
import { DEMO_PROPS, fixtureById, fixtureProps, GALLERY, sizeOf, wantsGallery } from '@silverpoint/example-harness';
import { SilverpointProvider } from '@silverpoint/react';
import { LineChart } from '@silverpoint/react/line-chart';
import { BulletChart } from '@silverpoint/react/bullet-chart';
import { PyramidChart } from '@silverpoint/react/pyramid-chart';
import { HeatmapChart } from '@silverpoint/react/heatmap-chart';
import { TreemapChart } from '@silverpoint/react/treemap-chart';
import { SankeyChart } from '@silverpoint/react/sankey-chart';
import { ActivityGrid } from '@silverpoint/react/activity-grid';
import { StepChart } from '@silverpoint/react/step-chart';
import { SparklineRows } from '@silverpoint/react/sparkline-rows';
import { KpiCard } from '@silverpoint/react/kpi-card';
import { BarChart } from '@silverpoint/react/bar-chart';
import { StackedBarChart } from '@silverpoint/react/stacked-bar-chart';
import { ComposedChart } from '@silverpoint/react/composed-chart';
import { WaterfallChart } from '@silverpoint/react/waterfall-chart';
import { FunnelChart } from '@silverpoint/react/funnel-chart';
import { CandlestickChart } from '@silverpoint/react/candlestick-chart';
import { AreaChart } from '@silverpoint/react/area-chart';
import { RangeBandChart } from '@silverpoint/react/range-band-chart';
import { StreamChart } from '@silverpoint/react/stream-chart';
import { ScatterChart } from '@silverpoint/react/scatter-chart';
import { BubbleChart } from '@silverpoint/react/bubble-chart';
import { DonutChart } from '@silverpoint/react/donut-chart';
import { RadarChart } from '@silverpoint/react/radar-chart';
import { PolarBarChart } from '@silverpoint/react/polar-bar-chart';
import { RadialArcGroup } from '@silverpoint/react/radial-arc-group';
import { RadialRings } from '@silverpoint/react/radial-rings';
import { GaugeArc } from '@silverpoint/react/gauge-arc';
import { MeterChart } from '@silverpoint/react/meter-chart';
import { CoxcombChart } from '@silverpoint/react/coxcomb-chart';
import { WindRose } from '@silverpoint/react/wind-rose';
import { VolvelleChart } from '@silverpoint/react/volvelle-chart';
import { ChordRing } from '@silverpoint/react/chord-ring';
import { OrbitChart } from '@silverpoint/react/orbit-chart';
import { LineChart as ServerLineChart } from '@silverpoint/react/server/line-chart';
import { StrictMode } from 'react';
import { createRoot } from 'react-dom/client';

// Every subpath this app imports — the barrel, the client entry and the server entry — must
// resolve the same way under `vite dev` and `vite build` (REQ-033, T-024).
const fixture = fixtureById(new URLSearchParams(location.search).get('fixture'));

/** Every chart a fixture can name, by its chart name. */
/** Every chart a fixture can name. A fixture's props fit its own chart; the union cannot say so. */
const CHARTS: Readonly<Record<string, ComponentType<Record<string, unknown>>>> = { LineChart, BulletChart, PyramidChart, HeatmapChart, TreemapChart, SankeyChart, ActivityGrid, StepChart, SparklineRows, KpiCard, BarChart, StackedBarChart, ComposedChart, WaterfallChart, FunnelChart, CandlestickChart, AreaChart, RangeBandChart, StreamChart, ScatterChart, BubbleChart, DonutChart, RadarChart, PolarBarChart, RadialArcGroup, RadialRings, GaugeArc, MeterChart, CoxcombChart, WindRose, VolvelleChart, ChordRing, OrbitChart } as unknown as Readonly<Record<string, ComponentType<Record<string, unknown>>>>;

function App() {
  if (wantsGallery(location.search)) {
    return (
      <main>
        <h1>silverpoint · Vite + React · gallery</h1>
        <div className="sp-gallery">
          {GALLERY.map(({ chart, props }) => {
            const Chart = CHARTS[chart]!;
            return (
              <div className="sp-harness" data-size="md" key={chart}>
                <Chart {...props} />
              </div>
            );
          })}
        </div>
      </main>
    );
  }
  if (fixture) {
    const FixtureChart = CHARTS[fixture.chart]!;
    return (
      <main>
        <div className="sp-harness" data-gate="" data-size={sizeOf(fixture)}>
          <FixtureChart {...fixtureProps(fixture)} />
        </div>
      </main>
    );
  }
  return (
    <SilverpointProvider substrate="cream">
      <main>
        <h1>silverpoint · Vite + React</h1>
        <div className="sp-harness" data-size="md">
          <LineChart {...DEMO_PROPS} />
        </div>
        <section className="sp-server">
          <ServerLineChart {...DEMO_PROPS} id="sp-demo-server" width={320} height={120} mode="precision" />
        </section>
      </main>
    </SilverpointProvider>
  );
}

createRoot(document.getElementById('root') as HTMLElement).render(
  <StrictMode>
    <App />
  </StrictMode>,
);
