// examples/vite-vue/src/App.vue
<script setup lang="ts">
import { DEMO_PROPS, fixtureProps, GALLERY, type HarnessFixture } from '@silverpoint/example-harness';
import { SpLineChart } from '@silverpoint/vue/line-chart';
import { SpBulletChart } from '@silverpoint/vue/bullet-chart';
import { SpPyramidChart } from '@silverpoint/vue/pyramid-chart';
import { SpHeatmapChart } from '@silverpoint/vue/heatmap-chart';
import { SpTreemapChart } from '@silverpoint/vue/treemap-chart';
import { SpSankeyChart } from '@silverpoint/vue/sankey-chart';
import { SpActivityGrid } from '@silverpoint/vue/activity-grid';
import { SpStepChart } from '@silverpoint/vue/step-chart';
import { SpSparklineRows } from '@silverpoint/vue/sparkline-rows';
import { SpKpiCard } from '@silverpoint/vue/kpi-card';
import { SpBarChart } from '@silverpoint/vue/bar-chart';
import { SpStackedBarChart } from '@silverpoint/vue/stacked-bar-chart';
import { SpComposedChart } from '@silverpoint/vue/composed-chart';
import { SpWaterfallChart } from '@silverpoint/vue/waterfall-chart';
import { SpFunnelChart } from '@silverpoint/vue/funnel-chart';
import { SpCandlestickChart } from '@silverpoint/vue/candlestick-chart';
import { SpAreaChart } from '@silverpoint/vue/area-chart';
import { SpRangeBandChart } from '@silverpoint/vue/range-band-chart';
import { SpStreamChart } from '@silverpoint/vue/stream-chart';
import { SpScatterChart } from '@silverpoint/vue/scatter-chart';
import { SpBubbleChart } from '@silverpoint/vue/bubble-chart';

const props = defineProps<{ fixture?: HarnessFixture; gallery?: boolean }>();

/** Every chart a fixture can name, by its chart name. */
const CHARTS = { LineChart: SpLineChart, BulletChart: SpBulletChart, PyramidChart: SpPyramidChart, HeatmapChart: SpHeatmapChart, TreemapChart: SpTreemapChart, SankeyChart: SpSankeyChart, ActivityGrid: SpActivityGrid, StepChart: SpStepChart, SparklineRows: SpSparklineRows, KpiCard: SpKpiCard, BarChart: SpBarChart, StackedBarChart: SpStackedBarChart, ComposedChart: SpComposedChart, WaterfallChart: SpWaterfallChart, FunnelChart: SpFunnelChart, CandlestickChart: SpCandlestickChart, AreaChart: SpAreaChart, RangeBandChart: SpRangeBandChart, StreamChart: SpStreamChart, ScatterChart: SpScatterChart, BubbleChart: SpBubbleChart } as const;
</script>

<template>
  <main v-if="props.fixture">
    <div class="sp-harness" data-gate="" data-size="md">
      <component :is="CHARTS[props.fixture.chart as keyof typeof CHARTS]" v-bind="fixtureProps(props.fixture)" />
    </div>
  </main>
  <main v-else-if="props.gallery">
    <h1>silverpoint · Vite + Vue · gallery</h1>
    <div class="sp-gallery">
      <div v-for="item in GALLERY" :key="item.chart" class="sp-harness" data-size="md">
        <component :is="CHARTS[item.chart as keyof typeof CHARTS]" v-bind="item.props" />
      </div>
    </div>
  </main>
  <main v-else>
    <h1>silverpoint · Vite + Vue</h1>
    <div class="sp-harness" data-size="md">
      <SpLineChart v-bind="DEMO_PROPS" />
    </div>
  </main>
</template>

// examples/nextjs/app/page.tsx
import { DEMO_PROPS, fixtureById, fixtureProps, GALLERY } from '@silverpoint/example-harness';
import { LineChart } from '@silverpoint/react/line-chart';
import { BulletChart } from '@silverpoint/react/bullet-chart';
import { PyramidChart } from '@silverpoint/react/pyramid-chart';
import { HeatmapChart } from '@silverpoint/react/heatmap-chart';
import { TreemapChart } from '@silverpoint/react/treemap-chart';
import { SankeyChart } from '@silverpoint/react/sankey-chart';
import { ActivityGrid } from '@silverpoint/react/activity-grid';
import { StepChart } from '@silverpoint/react/step-chart';
import { SparklineRows } from '@silverpoint/react/sparkline-rows';
import { KpiCard } from '@silverpoint/react/kpi-card';
import { BarChart } from '@silverpoint/react/bar-chart';
import { StackedBarChart } from '@silverpoint/react/stacked-bar-chart';
import { ComposedChart } from '@silverpoint/react/composed-chart';
import { WaterfallChart } from '@silverpoint/react/waterfall-chart';
import { FunnelChart } from '@silverpoint/react/funnel-chart';
import { CandlestickChart } from '@silverpoint/react/candlestick-chart';
import { AreaChart } from '@silverpoint/react/area-chart';
import { RangeBandChart } from '@silverpoint/react/range-band-chart';
import { StreamChart } from '@silverpoint/react/stream-chart';
import { ScatterChart } from '@silverpoint/react/scatter-chart';
import { BubbleChart } from '@silverpoint/react/bubble-chart';
import { LineChart as ServerLineChart } from '@silverpoint/react/server/line-chart';
import { Hydrated } from './hydrated';

/** Every chart a fixture can name, by its chart name. */
const CHARTS = { LineChart, BulletChart, PyramidChart, HeatmapChart, TreemapChart, SankeyChart, ActivityGrid, StepChart, SparklineRows, KpiCard, BarChart, StackedBarChart, ComposedChart, WaterfallChart, FunnelChart, CandlestickChart, AreaChart, RangeBandChart, StreamChart, ScatterChart, BubbleChart } as const;

export default async function Page({ searchParams }: { searchParams: Promise<Record<string, string | undefined>> }) {
  const params = await searchParams;
  if ('gallery' in params) {
    return (
      <main>
        <h1>silverpoint · Next.js (React) · gallery</h1>
        <div className="sp-gallery">
          {GALLERY.map(({ chart, props }) => {
            const Chart = CHARTS[chart as keyof typeof CHARTS];
            return (
              <div className="sp-harness" data-size="md" key={chart}>
                <Chart {...props} />
              </div>
            );
          })}
        </div>
        <Hydrated />
      </main>
    );
  }
  const fixture = fixtureById(params.fixture);
  if (fixture) {
    const FixtureChart = CHARTS[fixture.chart as keyof typeof CHARTS];
    return (
      <main>
        <div className="sp-harness" data-gate="" data-size="md">
          <FixtureChart {...fixtureProps(fixture)} />
        </div>
        <Hydrated />
      </main>
    );
  }
  return (
    <main>
      <h1>silverpoint · Next.js (React)</h1>
      <div className="sp-harness" data-size="md">
        <LineChart {...DEMO_PROPS} />
      </div>
      {/* A React Server Component: pure SVG, no client JavaScript (REQ-104). */}
      <section className="sp-server">
        <ServerLineChart {...DEMO_PROPS} id="sp-demo-server" width={320} height={120} mode="precision" />
      </section>
      <Hydrated />
    </main>
  );
}
